# Generated by Django 5.1 on 2024-08-21 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dismissed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=16, verbose_name='фамилия')),
                ('first_name', models.CharField(max_length=24, verbose_name='имя')),
                ('patronymic', models.CharField(blank=True, max_length=24, verbose_name='отчество')),
                ('division', models.CharField(max_length=64, verbose_name='Подразделение')),
                ('dismissed_from', models.DateField(blank=True, null=True, verbose_name='уволен с')),
                ('order', models.CharField(blank=True, max_length=64, null=True, verbose_name='чей приказ')),
                ('number', models.CharField(blank=True, max_length=16, null=True, verbose_name='приказ от')),
                ('an_arder_from', models.DateField(verbose_name='приказ от')),
            ],
        ),
    ]
