# Generated by Django 5.1 on 2024-08-21 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_dismissed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dismissed',
            name='an_arder_from',
            field=models.DateField(blank=True, null=True, verbose_name='приказ от'),
        ),
        migrations.AlterField(
            model_name='dismissed',
            name='number',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='номер приказа'),
        ),
    ]
