# Generated by Django 5.1 on 2024-08-21 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_dismissed_an_arder_from_alter_dismissed_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dismissed',
            old_name='an_arder_from',
            new_name='an_order_from',
        ),
    ]
