# Generated by Django 5.1 on 2024-08-21 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_an_arder_from_dismissed_an_order_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dismissed',
            name='number',
            field=models.IntegerField(blank=True, null=True, verbose_name='номер приказа'),
        ),
    ]
