# Generated by Django 5.1 on 2024-08-22 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_dismissed_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='excluded',
            field=models.BooleanField(default=False, verbose_name='исключен'),
        ),
    ]
